# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
