# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20180526_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingeridents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingerident', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='long_description',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='dish',
            name='short_description',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ingeridents',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.Dish'),
        ),
    ]
