# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20180528_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingeridents',
            new_name='Ingerident',
        ),
    ]
