# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_auto_20180528_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingerident',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingerident',
            new_name='ingredient',
        ),
    ]
