const keymirror = (keys) => {
  const obj = {};
  keys.forEach((key) => {
    obj[key] = key;
  });
  return obj;
}

export default keymirror([
  'DISH_LIST_FETCH_START',
  'DISH_LIST_FETCH_ERROR',
  'DISH_LIST_FETCH_SUCCESS',
  'ADD_DISH_START',
  'ADD_DISH_ERROR',
  'ADD_DISH_SUCCESS',
  'DISH_FETCH_START',
  'DISH_FETCH_SUCCESS',
  'DISH_FETCH_ERROR',
  'ADD_DISH_INFO_START',
  'ADD_DISH_INFO_ERROR',
  'ADD_DISH_INFO_SUCCESS',
  'FIVE_DAYS_PLANS_LIST_FETCH_START',
  'FIVE_DAYS_PLANS_LIST_FETCH_ERROR',
  'FIVE_DAYS_PLANS_LIST_FETCH_SUCCESS',
  'THREE_DAYS_PLANS_LIST_FETCH_START',
  'THREE_DAYS_PLANS_LIST_FETCH_ERROR',
  'THREE_DAYS_PLANS_LIST_FETCH_SUCCESS',
  'TIFFIN_PLAN_FETCH_START',
  'TIFFIN_PLAN_FETCH_ERROR',
  'TIFFIN_PLAN_FETCH_SUCCESS',
  'PLANS_LIST_FETCH_START',
  'PLANS_LIST_FETCH_ERROR',
  'PLANS_LIST_FETCH_SUCCESS',
  'CHECK_CUSTOMER_START',
  'CHECK_CUSTOMER_ERROR',
  'EMAIL_ALREADY_USED',
  'EMAIL_NOT_USED',
  'ADD_CUSTOMER_START',
  'ADD_CUSTOMER_ERROR',
  'ADD_CUSTOMER_SUCCESS',
]);