# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
