# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180703_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='us_state',
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_day',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_of_dishes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
