# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='restaurant',
        ),
    ]
