# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='restaurant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
