# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20180717_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('skipped', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('charged', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
    ]
