# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('customers', '0009_customer_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_week',
            name='week',
        ),
        migrations.AddField(
            model_name='customer_week',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Plan'),
        ),
    ]
