# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20180717_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFoodPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('special_instruction', models.CharField(blank=True, max_length=500)),
                ('is_vegeterian', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('plan_type', models.CharField(blank=True, max_length=100)),
                ('number_of_dishes', models.CharField(blank=True, max_length=100)),
                ('delivery_day', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('stripe_token', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('restaurant_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('zipcode', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('us_state', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
                ('skipped', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('charged', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_week',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer_week',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_day',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='number_of_dishes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='special_instruction',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='token',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='us_state',
        ),
        migrations.DeleteModel(
            name='Customer_Week',
        ),
    ]
