# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20180719_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
