# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-02 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customer_is_in_servicable_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyOrder',
        ),
    ]
