# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-04 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_delete_weeklyorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpayment',
            name='stripe_token',
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='card_expiration_month',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='card_expiration_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='card_name',
            field=models.CharField(default='Sudip Paudel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='card_type',
            field=models.CharField(default='Visa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='last_4',
            field=models.IntegerField(default=4242),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='stripe_customer_id',
            field=models.CharField(default='CUS_123', max_length=100),
            preserve_default=False,
        ),
    ]
