# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_auto_20180904_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermealplan',
            name='delivery_day',
        ),
        migrations.AddField(
            model_name='customermealplan',
            name='price_shipping',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customermealplan',
            name='price_weekly',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_day',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
