# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('price', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('is_vegeterian', models.BooleanField(default=False)),
                ('calorie', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[(b'3day', b'3day'), (b'5day', b'5day')], max_length=10)),
                ('price', models.CharField(max_length=100)),
                ('week', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish51', to='restaurant.Dish')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('rating_number', models.PositiveSmallIntegerField(blank=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('logo_url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res3', to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
