# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-28 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=100)),
                ('dish_id', models.CharField(max_length=100)),
                ('week', models.DateField()),
                ('three_day_plan_default', models.BooleanField(default=False)),
                ('five_day_plan_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating_number',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='foursquare_score',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='google_score',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='link_to_foursquare_score',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='link_to_google_score',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='link_to_yelp_score',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yelp_score',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanItems',
        ),
    ]
