# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180728_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.CharField(max_length=100)),
                ('three_day_plan_default', models.BooleanField(default=False)),
                ('five_day_plan_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='dish_id',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='five_day_plan_default',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='three_day_plan_default',
        ),
        migrations.AddField(
            model_name='weeklymenuitem',
            name='weeklymenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.WeeklyMenu'),
        ),
    ]
