# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180730_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymenuitem',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Dish'),
        ),
    ]
