# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20180730_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklymenuitem',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RemoveField(
            model_name='weeklymenuitem',
            name='weeklymenu',
        ),
        migrations.AddField(
            model_name='weeklymenuitem',
            name='weeklymenu_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
