# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_weeklymenu_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklymenu',
            name='is_active',
        ),
    ]
