# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('weeklymenu_id', models.IntegerField()),
                ('skipped', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('charged', models.BooleanField(default=False)),
            ],
        ),
    ]
