# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklyorder_id', models.IntegerField()),
                ('dish_id', models.IntegerField()),
            ],
        ),
    ]
