# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyorder', '0002_weeklyorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyorder',
            name='restaurant_id',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyorder',
            name='week_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
